# Generated by Django 5.2.10 on 2026-01-30 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("transcription", models.TextField()),
                ("relevance_score", models.FloatField(default=0.0)),
                ("technical_depth_score", models.FloatField(default=0.0)),
                ("clarity_score", models.FloatField(default=0.0)),
                ("communication_score", models.FloatField(default=0.0)),
                ("final_score", models.FloatField(default=0.0)),
                ("ai_feedback", models.TextField(blank=True, null=True)),
                ("tab_switch_count", models.IntegerField(default=0)),
                ("is_suspicious", models.BooleanField(default=False)),
                ("cheating_flags", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="core.interview",
                    ),
                ),
            ],
        ),
    ]
