# Generated by Django 5.2.1 on 2025-05-23 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('current_stage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('consistently_flags_inaccurate_ai', models.BooleanField(default=False)),
                ('uses_scoring', models.BooleanField(default=True)),
                ('reviews_results', models.BooleanField(default=True)),
                ('total_interviews_conducted', models.IntegerField(default=0)),
                ('total_hires', models.IntegerField(default=0)),
                ('time_saved_vs_traditional', models.DurationField(blank=True, null=True)),
                ('roi_signals', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=255)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Invited', 'Invited'), ('Started', 'Started'), ('Completed', 'Completed'), ('Shortlisted', 'Shortlisted'), ('Selected', 'Selected')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('abandoned', models.BooleanField(default=False)),
                ('device_type', models.CharField(choices=[('Desktop', 'Desktop'), ('Mobile', 'Mobile'), ('Tablet', 'Tablet')], max_length=20)),
                ('browser_type', models.CharField(choices=[('Chrome', 'Chrome'), ('Firefox', 'Firefox'), ('Safari', 'Safari'), ('Edge', 'Edge'), ('Other', 'Other')], max_length=20)),
                ('platform_type', models.CharField(choices=[('Web', 'Web'), ('iOS', 'iOS'), ('Android', 'Android')], max_length=20)),
                ('interview_type', models.CharField(choices=[('Technical', 'Technical'), ('Behavioral', 'Behavioral')], max_length=20)),
                ('questions_used', models.TextField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.candidate')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employer')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('text', models.TextField()),
                ('ai_flagged_inaccurate', models.BooleanField(default=False)),
                ('complaint_raised', models.BooleanField(default=False)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.interview')),
            ],
        ),
        migrations.CreateModel(
            name='SystemIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employer')),
            ],
        ),
    ]
